# Generated by Django 4.1.4 on 2022-12-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('unique_code', models.IntegerField(unique=True)),
                ('Size', models.CharField(choices=[(10, '10'), (20, '20'), (30, '30')], max_length=20)),
                ('Quality', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('meduim', 'medium')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hai.productmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='productColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], max_length=20)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hai.productmainmodel')),
            ],
        ),
    ]
